# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
"""
Ultralytics neural network modules.

This module provides access to various neural network components used in Ultralytics models, including convolution
blocks, attention mechanisms, transformer components, and detection/segmentation heads.

Examples:
    Visualize a module with Netron
    >>> from ultralytics.nn.modules import Conv
    >>> import torch
    >>> import subprocess
    >>> x = torch.ones(1, 128, 40, 40)
    >>> m = Conv(128, 128)
    >>> f = f"{m._get_name()}.onnx"
    >>> torch.onnx.export(m, x, f)
    >>> subprocess.run(f"onnxslim {f} {f} && open {f}", shell=True, check=True)  # pip install onnxslim
"""

from .block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    A2C2f,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C2fCIB,
    C2fPSA,
    C3Ghost,
    C3k2,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    MaxSigmoidAttnBlock,
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    TorchVision,
    APFN,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    Index,
    LightConv,
    RepConv,
    SpatialAttention,
)
from .head import (
    OBB,
    OBB26,
    Classify,
    Detect,
    LRPCHead,
    Pose,
    Pose26,
    RTDETRDecoder,
    Segment,
    SegmentCitrusAux,
    SegmentCitrusBLite,
    SegmentCitrusBQuality,
    SegmentCitrusDualProto,
    SegmentCitrusLite,
    SegmentCitrusLiteBQ,
    SegmentCitrusQualityLite,
    SegmentCitrusSDR,
    SegmentCitrusTopo,
    SegmentP2Boundary,
    SegmentP2CFS,
    SegmentP2DetectBoundary,
    Segment26,
    SemanticSegment,
    WorldDetect,
    YOLOEDetect,
    YOLOESegment,
    YOLOESegment26,
    v10Detect,
)
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)
from .ct_modules import (
    APFM,
    BLFLoss,
    BypassModule,
    ESOFusion,
    IDAPBCFusion,
    KalmanGatedFusion,
    MultiScaleVarianceEstimator,
)
from .lsnet import (
    LSBlock,
    LSConv,
    LSNetBackbone,
    LSNetDownsample,
    LSNet_B,
    LSNet_S,
    LSNet_T,
    MSAStageBlock,
    PatchEmbed,
)
from .shufflenetv2_depth import (
    ShuffleV2Block,
    ShuffleV2Stage,
    ShuffleV2Stem_Depth,
)
from .custom_blocks import (
    DGFFN,
    HaarDWT,
    HaarIDWT,
    SFM,
    WCAF,
)
from .rgbd_fusion_neck import (
    FusionDecoder,
    P3FusionModule,
    P4FusionModule,
    P5FusionModule,
    RGBDFusionNeck,
    ScaleAlignBlock,
)
from .mobilenetv3_rgb import (
    MobileNetV3InvertedResidual,
    MobileNetV3Stage,
    MobileNetV3Stem_RGB,
)
from .mobilenetv4_rgb import (
    FusedIB,
    MobileNetV4Stage,
    MobileNetV4Stem_RGB,
    UIBBlock,
)
from .starnet_depth import (
    StarBlock,
    StarNetStage,
    StarNetStem_Depth,
)
from .starnet import (
    STARNET_VARIANTS,
    StarConvBN,
    StarNetBackbone,
    StarNetBlock,
)
from .scale_aware_fusion import (
    ScaleAwareFusion,
    ScaleAwareFusion_Bidirectional,
    ScaleAwareFusion_Depth2RGB,
    ScaleAwareFusion_Naive,
    ScaleAwareFusion_RGBLed,
)
from .mano import (
    C2MANO,
    MANOBlock,
    MultipoleAttention,
)
from .hvi_enhance import (
    HVIEnhance,
    IELBlock,
    RGBHVI,
)
from .p2_cfs_attention import P2CFSAttention
from .citrus_topo import (
    CitrusBoundaryFusion,
    CitrusBoundaryQueryAux,
    CitrusScaleFusion,
    CitrusTrainAux,
    SPPFLSKAResidual,
    SPPFRepContext,
)
from .citrus_b import CitrusDetailInject, CitrusPagFM, LiteHRDetailBlock
from .citrus_c import CitrusTopologyPrototype
from .citrus_d import CitrusShapeFusion, CitrusShapeStream, CitrusStructureStem
from .citrus_g0830 import CitrusBilateralExchange, CitrusFrequencyAlignedConcat, CitrusRepMixerStage
from .citrus_g0839 import CitrusDualResolutionBackbone, CitrusSDRSupport
from .citrus_light import CitrusLightAFPN, CitrusLightStage
from .citrus_savss import CitrusSAVSS, FrequencyAwareDown
from .citrus_far import (
    AAFM,
    BiFPNConcat,
    C3k2_DWR,
    C3k2_Faster,
    C3k2_LS,
    C3k2_MoCE,
    C3k2_SXQ,
    C3k2_WT,
    CAA,
    CARAFE,
    CSFG,
    CoordAtt,
    DFEM,
    DWR,
    DySample,
    DyT,
    ELA,
    EMA,
    FarFormer,
    FasterBlock,
    HCO,
    HSF,
    HWDown,
    HyperACE,
    HyperRes,
    LCE,
    LIAM,
    LSKA,
    LumiFormer,
    MWCA,
    PCFA,
    PConv,
    RFB,
    SPDConv,
    SPPF_LSKA,
    SimAM,
    TDAM,
    TGP,
    WTBottleneck,
    WTConv,
)

__all__ = (
    "AIFI",
    "C1",
    "C2",
    "C2PSA",
    "C3",
    "C3TR",
    "CBAM",
    "CIB",
    "DFL",
    "ELAN1",
    "MLP",
    "OBB",
    "OBB26",
    "PSA",
    "SPP",
    "SPPELAN",
    "SPPF",
    "A2C2f",
    "AConv",
    "ADown",
    "Attention",
    "BNContrastiveHead",
    "Bottleneck",
    "BottleneckCSP",
    "C2f",
    "C2fAttn",
    "C2fCIB",
    "C2fPSA",
    "C3Ghost",
    "C3k2",
    "C3k2_Faster",
    "C3k2_DWR",
    "C3k2_LS",
    "C3k2_MoCE",
    "C3k2_SXQ",
    "C3k2_WT",
    "C3x",
    "CBFuse",
    "CBLinear",
    "ChannelAttention",
    "Classify",
    "Concat",
    "CARAFE",
    "CAA",
    "CSFG",
    "CoordAtt",
    "DFEM",
    "DWR",
    "DySample",
    "DyT",
    "ELA",
    "EMA",
    "FarFormer",
    "FasterBlock",
    "HCO",
    "HSF",
    "HWDown",
    "AAFM",
    "HyperACE",
    "HyperRes",
    "LCE",
    "LIAM",
    "LSKA",
    "LumiFormer",
    "MWCA",
    "PCFA",
    "PConv",
    "RFB",
    "SPDConv",
    "SimAM",
    "TDAM",
    "TGP",
    "WTBottleneck",
    "WTConv",
    "ContrastiveHead",
    "Conv",
    "Conv2",
    "ConvTranspose",
    "DWConv",
    "DWConvTranspose2d",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "Detect",
    "Focus",
    "GhostBottleneck",
    "GhostConv",
    "HGBlock",
    "HGStem",
    "ImagePoolingAttn",
    "Index",
    "LRPCHead",
    "LayerNorm2d",
    "LightConv",
    "MLPBlock",
    "MSDeformAttn",
    "MaxSigmoidAttnBlock",
    "Pose",
    "Pose26",
    "P2CFSAttention",
    "BiFPNConcat",
    "CitrusBoundaryFusion",
    "CitrusDetailInject",
    "CitrusPagFM",
    "CitrusSAVSS",
    "CitrusShapeFusion",
    "CitrusShapeStream",
    "CitrusBilateralExchange",
    "CitrusFrequencyAlignedConcat",
    "CitrusRepMixerStage",
    "CitrusDualResolutionBackbone",
    "CitrusSDRSupport",
    "CitrusLightAFPN",
    "CitrusLightStage",
    "CitrusStructureStem",
    "FrequencyAwareDown",
    "CitrusScaleFusion",
    "CitrusBoundaryQueryAux",
    "CitrusTrainAux",
    "CitrusTopologyPrototype",
    "LiteHRDetailBlock",
    "SPPFLSKAResidual",
    "SPPF_LSKA",
    "SPPFRepContext",
    "Proto",
    "RTDETRDecoder",
    "RepC3",
    "RepConv",
    "RepNCSPELAN4",
    "RepVGGDW",
    "ResNetLayer",
    "SCDown",
    "Segment",
    "SegmentCitrusAux",
    "SegmentCitrusBLite",
    "SegmentCitrusBQuality",
    "SegmentCitrusDualProto",
    "SegmentCitrusLite",
    "SegmentCitrusLiteBQ",
    "SegmentCitrusQualityLite",
    "SegmentCitrusSDR",
    "SegmentCitrusTopo",
    "SegmentP2Boundary",
    "SegmentP2CFS",
    "SegmentP2DetectBoundary",
    "Segment26",
    "SemanticSegment",
    "SpatialAttention",
    "TorchVision",
    "TransformerBlock",
    "TransformerEncoderLayer",
    "TransformerLayer",
    "WorldDetect",
    "YOLOEDetect",
    "YOLOESegment",
    "YOLOESegment26",
    "v10Detect",
    # CT fusion modules
    "APFM",
    "BLFLoss",
    "BypassModule",
    "ESOFusion",
    "IDAPBCFusion",
    "KalmanGatedFusion",
    "MultiScaleVarianceEstimator",
    # LSNet backbone
    "LSBlock",
    "LSConv",
    "LSNetBackbone",
    "LSNetDownsample",
    "LSNet_B",
    "LSNet_S",
    "LSNet_T",
    "MSAStageBlock",
    "PatchEmbed",
    # ShuffleNetV2 depth branch
    "ShuffleV2Block",
    "ShuffleV2Stage",
    "ShuffleV2Stem_Depth",
    # Custom RGB-D modules
    "DGFFN",
    "HaarDWT",
    "HaarIDWT",
    "SFM",
    "WCAF",
    # RGBD Fusion Neck
    "FusionDecoder",
    "P3FusionModule",
    "P4FusionModule",
    "P5FusionModule",
    "RGBDFusionNeck",
    "ScaleAlignBlock",
    # MobileNetV3 RGB branch
    "MobileNetV3InvertedResidual",
    "MobileNetV3Stage",
    "MobileNetV3Stem_RGB",
    # MobileNetV4 RGB branch
    "FusedIB",
    "MobileNetV4Stage",
    "MobileNetV4Stem_RGB",
    "UIBBlock",
    # StarNet depth branch
    "StarBlock",
    "StarNetStage",
    "StarNetStem_Depth",
    # Official StarNet backbone
    "STARNET_VARIANTS",
    "StarConvBN",
    "StarNetBackbone",
    "StarNetBlock",
    # Scale-Aware Fusion
    "ScaleAwareFusion",
    "ScaleAwareFusion_Bidirectional",
    "ScaleAwareFusion_Depth2RGB",
    "ScaleAwareFusion_Naive",
    "ScaleAwareFusion_RGBLed",
    # MANO multipole attention
    "C2MANO",
    "MANOBlock",
    "MultipoleAttention",
    # HVI low-light enhancement front-end
    "HVIEnhance",
    "IELBlock",
    "RGBHVI",
)
