from .config import ACTIVATION_MAP, RESNET_18_CFG, RESNET_18_BACKBONE_CFG, RESNET_34_CFG

__all__ = [
    "ACTIVATION_MAP", 
    "RESNET_18_CFG", 
    "RESNET_18_BACKBONE_CFG", 
    "RESNET_34_CFG"
    ]
